### ISSUE TITLE
Sidebar doesn't update.

### ISSUE THREAD

**Issue by olafveerman** [worldbank-cdrp/disaster-risk-explorer#6]
Bug reported by Xijie.

![image](https://cloud.githubusercontent.com/assets/751330/24463959/44b55338-14a0-11e7-8e9b-a3f157dc76f8.png)

To replicate:

1. go to: https://worldbank-cdrp.github.io/disaster-risk-explorer/#/en
2. select an area
3. change to exposure
4. select another area

**Comment by olafveerman** [comment]
cc @nbumbarger @DylanMoriarty @drewbo

**Comment by DylanMoriarty** [comment]
Looks like this is failing because there aren't values for the bar chart x-axis for the exposure view.
