### ISSUE TITLE
Discrepencies in overall aal

### ISSUE THREAD

**Issue by olafveerman** [worldbank-cdrp/disaster-risk-explorer#7]
Reported by Xijie:

> Please see the screenshots below. When I put two tabs side by side to show the same country/region with the same conversion settings, the reduction of AAL is always different with quite big discrepancy. Fortunately, the other results metrics remain the same.

![image](https://cloud.githubusercontent.com/assets/751330/24464207/0e71e63c-14a1-11e7-82d5-608091834dff.png)

![image](https://cloud.githubusercontent.com/assets/751330/24464238/2100f43c-14a1-11e7-8149-2abcc27fe53d.png)

![image](https://cloud.githubusercontent.com/assets/751330/24464244/247fae0a-14a1-11e7-8f00-e9ddc75da126.png)

cc @nbumbarger @DylanMoriarty @drewbo

**Comment by xijielu** [comment]
In addition, the unit cost of replacement/retrofitting should be USD/sq m

**Comment by xijielu** [comment]
Also,  can we change the coloring for the retrofit and replace button. The active one is greyed out, which is a bit counter-intuitive.

**Comment by mileswwatkins** [comment]
Steps to repeat; took me a bit to figure out, for the purposes of debugging, since it doesn't always happen cross-session/-browser:

- open tool
- click on one country
- launch the calculator
- observe the AAL
- exit the calculator, click on a _different_ country, launch the calculator, and observe the AAL for the original country

The values will be different. I have some hunches!

**Comment by mileswwatkins** [comment]
Looks like the value of `calculator-modal`'s `aal` is set using `this.props.attributes`, which comes from `home.js`'s `this.props.selected`, which is updated by the `UPDATE_SELECTED` reducer, which is dispatched by the `map.js`'s `_mapClick` function.

The data are drawn from the map's vector tiles, but from two different layers (one for each admin layer). So, we can't get the data using a `querySourceFeatures` or the like.

@drewbo has some pre-processed GeoJSON data that the vector tiles are based on, which he'll give me and I can process down to a JSON that we could grab on-page-load and use in the calculator, in place of this invariant `aal`.

**Comment by mileswwatkins** [comment]
Drew can give me this data when he returns to DC, so I'll close out this bug sometime next week.

**Comment by mileswwatkins** [comment]
Data forthcoming soon, but I won't likely get to address this bug this week.

**Comment by malhern** [comment]
Hi Miles--thanks!
The error seems to arise when you launch the building calculator by clicking a country first and then select a subregion vs when you click on a subregion on the map and launch building calculator directly from there.

**Comment by mileswwatkins** [comment]
@malhern, I did my own checks, but can you confirm that this bug is closed out? Let me know if you see any remaining issues.

**Comment by malhern** [comment]
@mileswwatkins Still seeing the AAL discrepancy between clicking on the subregion itself vs selecting the area within the calculator

<img width="738" alt="aal" src="https://user-images.githubusercontent.com/29928091/28374562-24310140-6c73-11e7-8622-39936105aced.PNG">
<img width="741" alt="aal0" src="https://user-images.githubusercontent.com/29928091/28374565-269864fa-6c73-11e7-9222-1b7395541c6c.PNG">

**Comment by mileswwatkins** [comment]
Ah, my mistake @malhern; can you look now? The deployed website hadn't updated until this afternoon.

**Comment by malhern** [comment]
Ok just checked and it looks good. Thanks!
